### ISSUE TITLE
Les cridades a createAndStartPeticioDeFirma de l'API V1 genera un NullPointerException

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#329]
Log de l'error

2019-08-29 08:30:11,062 INFO  [es.caib.portafib.ws.utils.PortaFIBInInterceptor] (http-10.215.9.173-18080-7)  ROLE: PFI_ADMIN  false
2019-08-29 08:30:11,062 INFO  [es.caib.portafib.ws.utils.PortaFIBInInterceptor] (http-10.215.9.173-18080-7)  ROLE: PFI_USER  true
2019-08-29 08:30:11,062 INFO  [es.caib.portafib.ws.utils.PortaFIBInInterceptor] (http-10.215.9.173-18080-7) PortaFIBInInterceptor::handleMessage() =>  Thread = 134
2019-08-29 08:30:11,062 INFO  [es.caib.portafib.ws.utils.PortaFIBInInterceptor] (http-10.215.9.173-18080-7) PortaFIBInInterceptor::handleMessage() => user $asnotif2_portafib
2019-08-29 08:30:11,062 INFO  [es.caib.portafib.ws.utils.PortaFIBInInterceptor] (http-10.215.9.173-18080-7) PortaFIBInInterceptor::handleMessage() => PFI_USER true
2019-08-29 08:30:11,062 INFO  [es.caib.portafib.ws.utils.PortaFIBInInterceptor] (http-10.215.9.173-18080-7) PortaFIBInInterceptor::handleMessage() => PFI_ADMIN false
2019-08-29 08:30:11,073 INFO  [es.caib.portafib.ws.utils.PortaFIBInInterceptor] (http-10.215.9.173-18080-7) PortaFIBInInterceptor::handleMessage() Usuari APP = $asnotif2_portafib
2019-08-29 08:30:11,078 INFO  [es.caib.portafib.ws.v1.impl.PortaFIBPeticioDeFirmaWsImpl] (http-10.215.9.173-18080-7)  XYZ ZZZ  fileToConvertInfo = es.caib.portafib.ws.v1.impl.FitxerBean@100d7120
2019-08-29 08:30:11,094 INFO  [es.caib.portafib.ws.v1.utils.FitxerUtils] (http-10.215.9.173-18080-7)  TAMANY DE FITXER REBUT = 7252
2019-08-29 08:30:11,137 INFO  [es.caib.portafib.ws.v1.utils.FitxerUtils] (http-10.215.9.173-18080-7) ID FITXER CREAT = 532780
2019-08-29 08:30:11,293 DEBUG [es.caib.portafib.logic.utils.PdfUtils] (http-10.215.9.173-18080-7) convertToPDF(): Name = DOC_SGSERSOC_1567060095427
2019-08-29 08:30:11,293 DEBUG [es.caib.portafib.logic.utils.PdfUtils] (http-10.215.9.173-18080-7) convertToPDF(): File = /app/caib/portafib/532780
2019-08-29 08:30:11,293 DEBUG [es.caib.portafib.logic.utils.PdfUtils] (http-10.215.9.173-18080-7) convertToPDF(): File Exists?= true
2019-08-29 08:30:11,293 DEBUG [es.caib.portafib.logic.utils.PdfUtils] (http-10.215.9.173-18080-7) convertToPDF(): MIME = application/pdf
2019-08-29 08:30:11,326 DEBUG [es.caib.portafib.logic.FluxDeFirmesLogicaEJB] (http-10.215.9.173-18080-7) S'ha creat un fluxDeFirmes amb ID = 532781
2019-08-29 08:30:11,701 INFO  [es.caib.portafib.logic.CustodiaInfoLogicaEJB] (http-10.215.9.173-18080-7) XYZ ZZZ  getAllowedCustodyInfo:: ES USER APP (cridant a getCustodiaUA)
2019-08-29 08:30:11,711 DEBUG [es.caib.portafib.logic.PeticioDeFirmaLogicaEJB] (http-10.215.9.173-18080-7) PF[532784] = es.caib.portafib.jpa.PeticioDeFirmaJPA@351275f1
2019-08-29 08:30:11,711 DEBUG [es.caib.portafib.logic.PeticioDeFirmaLogicaEJB] (http-10.215.9.173-18080-7) PeticioDeFirma[532784] = es.caib.portafib.jpa.PeticioDeFirmaJPA@351275f1
2019-08-29 08:30:11,716 DEBUG [es.caib.portafib.logic.PeticioDeFirmaLogicaEJB] (http-10.215.9.173-18080-7) Current State = 0
2019-08-29 08:30:11,716 DEBUG [es.caib.portafib.logic.PeticioDeFirmaLogicaEJB] (http-10.215.9.173-18080-7) State NO INICIAT = 0
2019-08-29 08:30:11,716 ERROR [es.caib.portafib.logic.PeticioDeFirmaLogicaEJB] (http-10.215.9.173-18080-7) Error arrancant peticio de firma 532784
java.lang.NullPointerException
        at es.caib.portafib.logic.PeticioDeFirmaLogicaEJB.checkUsersOfFlux(PeticioDeFirmaLogicaEJB.java:1222)
        at es.caib.portafib.logic.PeticioDeFirmaLogicaEJB.start(PeticioDeFirmaLogicaEJB.java:815)

**Comment by areus-fundaciobit** [comment]
Corregir l'error.
Com a workaround fins alliberar la versió 2.0.1, es poden emprar les cridades de l'api per separat createPeticio i start

**Comment by areus-fundaciobit** [comment]
També s'ha detectat que fallen si la petició de firmes conté annexos
