### ISSUE TITLE
NoSuchMethodError cridant a JXADES d'AutoFirma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#347]
Fent feina amb el issue  Suportar XAdES a Firma Web, API Firma Simple Web i API Firma Simple Async #333, es produeix un error "java.lang.NoSuchMethodError: net.java.xades.security.xml.XAdES.XAdES.newInstance()" al cridar a Autofirma amb firmes XADES.

El mòdul afirma-server-triphase-signer-2.5.jar conté una classe es.gob.afirma.triphase.signer.xades.XAdESTriPhaseSignerServerSide que crida al mètode net.java.xades.security.xml.XAdES.XAdES.newInstance() del JAR JXADES-0.1.5.

Després de varis intents de modificar la versió de JXADES m'he adonat que la llibreia integra-1.3.1 inclou les classes de la llibreria JXADES i que aquestes es carreguen abans.

Recompilar es.gob.afirma.triphase.signer.xades.XAdESTriPhaseSignerServerSide.java per a que faci ús de .XAdES.newInstance() d' integra-1.3.1

Caused by: java.lang.NoSuchMethodError: net.java.xades.security.xml.XAdES.XAdES.newInstance(Lnet/java/xades/security/xml/XAdES/XAdES;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lorg/w3c/dom/Document;Lorg/w3c/dom/Element;)Lnet/java/xades/security/xml/XAdES/XAdES_BES;
	at es.gob.afirma.signers.xades.XAdESSigner.sign(XAdESSigner.java:1072)
	at es.gob.afirma.triphase.signer.xades.XAdESTriPhaseSignerServerSide.preSign(XAdESTriPhaseSignerServerSide.java:239)
	at es.gob.afirma.triphase.signer.processors.XAdESTriPhasePreProcessor.preProcessPre(XAdESTriPhasePreProcessor.java:148)
	at es.gob.afirma.triphase.signer.processors.XAdESTriPhasePreProcessor.preProcessPreSign(XAdESTriPhasePreProcessor.java:89)
	at es.gob.afirma.signers.batch.SingleSignPreProcessor.getPreSign(SingleSignPreProcessor.java:69)
	at es.gob.afirma.signers.batch.SingleSignPreProcessor.doPreProcess(SingleSignPreProcessor.java:34)
	at es.gob.afirma.signers.batch.SingleSign.doPreProcess(SingleSign.java:182)
	at es.gob.afirma.signers.batch.SignBatchSerial.doPreBatch(SignBatchSerial.java:43)
	at es.gob.afirma.signers.batch.server.BatchPresigner.service(BatchPresigner.java:150)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.fundaciobit.plugin.signatureweb.afirmatriphaseserver.AfirmaTriphaseSignatureWebPlugin.batchPreSigner(AfirmaTriphaseSignatureWebPlugin.java:2499)
	at org.fundaciobit.plugin.signatureweb.afirmatriphaseserver.AfirmaTriphaseSignatureWebPlugin.commonRequestGETPOST(AfirmaTriphaseSignatureWebPlugin.java:370)
	at org.fundaciobit.plugin.signatureweb.afirmatriphaseserver.AfirmaTriphaseSignatureWebPlugin.requestPOST(AfirmaTriphaseSignatureWebPlugin.java:345)
	at org.fundaciobit.plugins.signatureweb.api.AbstractSignatureWebPlugin.requestPOST(AbstractSignatureWebPlugin.java:276)
	at es.caib.portafib.back.controller.common.SignatureModuleController.requestPlugin(SignatureModuleController.java:448)
	at es.caib.portafib.back.controller.common.SignatureModuleController.processServlet(SignatureModuleController.java:367)
	at es.caib.portafib.back.controller.common.SignatureModuleController.doPost(SignatureModuleController.java:317)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:88)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at es.caib.portafib.back.security.ClientCertAuthenticationFilter.doFilter(ClientCertAuthenticationFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:190)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:525)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:92)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	... 8 more

**Comment by anadal-fundaciobit** [comment]
Solució temporal: afegides les dues versions de JXADES

**Comment by areus-fundaciobit** [comment]
desfet el canvi que afegia l'xmlsec a l'ear, i llevat també xml-security-impl, perquè funcioni amb les llibreries de jboss.
