### ISSUE TITLE
NullPointerException per mor de que es guarda un valor null dins una Notificacio

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#395]
null --------------------------------------------  java.lang.NullPointerException at  es.caib.portafib.logic.utils.NotificacioInfo.readNotificacioInfo(NotificacioInfo.java:55) at  es.caib.portafib.logic.misc.NotificacionsCallBackTimerEJB.processNotificacio(NotificacionsCallBackTimerEJB.java:298) at  es.caib.portafib.logic.misc.NotificacionsCallBackTimerEJB.executeTask(NotificacionsCallBackTimerEJB.java:266) at  es.caib.portafib.logic.misc.NotificacionsCallBackTimerEJB.timeOutHandler(NotificacionsCallBackTimerEJB.java:134) at sun.reflect.GeneratedMethodAccessor719.invoke(Unknown Source) at  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at  org.jboss.aop.joinpoint.MethodInvocation.invokeTarget(MethodInvocation.java:122) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:111) at  org.jboss.ejb3.entity.TransactionScopedEntityManagerInterceptor.invoke(TransactionScopedEntityManagerInterceptor.java:56) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.core.timer.EnlistTimerInterceptor.invoke(EnlistTimerInterceptor.java:68) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.AllowedOperationsInterceptor.invoke(AllowedOperationsInterceptor.java:47) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at org.jboss.ejb3.tx.NullInterceptor.invoke(NullInterceptor.java:42) at org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.stateless.StatelessInstanceInterceptor.invoke(StatelessInstanceInterceptor.java:68) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at org.jboss.aspects.tx.TxPolicy.invokeInOurTx(TxPolicy.java:79) at  org.jboss.aspects.tx.TxInterceptor$Required.invoke(TxInterceptor.java:190) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.aspects.tx.TxPropagationInterceptor.invoke(TxPropagationInterceptor.java:76) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.security.RunAsSecurityInterceptorv2.invoke(RunAsSecurityInterceptorv2.java:105) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.ENCPropagationInterceptor.invoke(ENCPropagationInterceptor.java:41) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.BlockContainerShutdownInterceptor.invoke(BlockContainerShutdownInterceptor.java:67) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.core.context.CurrentInvocationContextInterceptor.invoke(CurrentInvocationContextInterceptor.java:47) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.aspects.currentinvocation.CurrentInvocationInterceptor.invoke(CurrentInvocationInterceptor.java:67) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.interceptor.EJB3TCCLInterceptor.invoke(EJB3TCCLInterceptor.java:86) at  org.jboss.aop.joinpoint.MethodInvocation.invokeNext(MethodInvocation.java:102) at  org.jboss.ejb3.stateless.StatelessContainer.callTimeout(StatelessContainer.java:684) at  org.jboss.ejb3.stateless.StatelessContainer.callTimeout(StatelessContainer.java:200) at  org.jboss.as.ejb3.timerservice.TimedObjectInvokerBridge.callTimeout(TimedObjectInvokerBridge.java:44) at org.jboss.ejb.txtimer.TimerImpl$TimerTaskImpl.run(TimerImpl.java:694) at  java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) at  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) at  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745)
--

**Comment by areus-fundaciobit** [comment]
L'error es produeix a degut a que dins el camp "descripcio" de tipus CLOB de NotificacioWS s'emmagatzema un string buid/null (per Oracle és el mateix).

Passa amb qualsevol aplicació i amb diferents tipus de notificacions, però no passa sempre.

Revisat el codi que genera el valor del camp, funciona correctament, i en diferents proves no hem aconseguit que generi un valor buid o null.

Atès que el procés de creació de la notificació té lloc dins una transacció on primer es crea l'objecte, jutnament amb altres, i llavors es produeix un update que fixa el valor, sembla que podria ser degut a un problema dels drivers JDBC.

Aquí s'esmenta un cas similar: https://hibernate.atlassian.net/browse/HHH-2723

**Comment by areus-fundaciobit** [comment]
El següent script permet recuperar les notificacions més habituals:
 - Petició en procés
 - Firma parcial
 - Petició firmada
 - Petició rebutjada

[portafib-recover-descripcio-notificacio-oracle.sql.txt](https://github.com/GovernIB/portafib/files/3916457/portafib-recover-descripcio-notificacio-oracle.sql.txt)

**Comment by areus-fundaciobit** [comment]
Sembla que l'error era degut a un problema de configuració del datasource. Tancam
