### ISSUE TITLE
Cliente Movil @firma no funciona

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#427]
En Android (mòbil i Tablet) es produeix un error durant la firma: "Error durante el proceso de cifrado de datos". L'error es produeix  en l'APP móvil.
He provat d'actualizar el miniapplet.js, triphase server, retriever i storage i segueix amb el mateix error.
Un IPAD 2 amb un Client Antic (no es pot actualitzar) si que funciona, o sigui que la gent del Ministeri han actualitzat el client mòbil Android i l'han fet NO retrocompatible.

He fet un CAID al PAE i estic esperant. 

També he pogut depurar l'android  i surt la següent excepció:

04-29 11:28:00.892 12314-12351/? E/es.gob.afirma: Error durante la operacion de firma: es.gob.afirma.signers.pades.InvalidPdfException: El fichero no es un PDF o es un PDF no soportado
es.gob.afirma.signers.pades.InvalidPdfException: El fichero no es un PDF o es un PDF no soportado
 at es.gob.afirma.signers.pades.PdfUtil.getPdfReader(PdfUtil.java:180)
 at es.gob.afirma.signers.pades.PdfSessionManager.getSessionData(PdfSessionManager.java:253)
 at es.gob.afirma.signers.pades.PAdESTriPhaseSigner.preSign(PAdESTriPhaseSigner.java:183)
 at es.gob.afirma.signers.pades.AOPDFSigner.sign(AOPDFSigner.java:179)
 at es.gob.afirma.android.crypto.SignTask.doInBackground(SignTask.java:111)
 at es.gob.afirma.android.crypto.SignTask.doInBackground(SignTask.java:38)
 at android.os.AsyncTask$2.call(AsyncTask.java:295)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException: PDF header signature not found.
 at com.aowagie.text.pdf.PRTokeniser.checkPdfHeader(PRTokeniser.java:199)
 at com.aowagie.text.pdf.PdfReader.readPdf(PdfReader.java:462)
 at com.aowagie.text.pdf.PdfReader.<init>(PdfReader.java:187)
 at com.aowagie.text.pdf.PdfReader.<init>(PdfReader.java:176)
 at es.gob.afirma.signers.pades.PdfUtil.getPdfReader(PdfUtil.java:148)
 at es.gob.afirma.signers.pades.PdfSessionManager.getSessionData(PdfSessionManager.java:253)
 at es.gob.afirma.signers.pades.PAdESTriPhaseSigner.preSign(PAdESTriPhaseSigner.java:183)
 at es.gob.afirma.signers.pades.AOPDFSigner.sign(AOPDFSigner.java:179)
 at es.gob.afirma.android.crypto.SignTask.doInBackground(SignTask.java:111)
 at es.gob.afirma.android.crypto.SignTask.doInBackground(SignTask.java:38)
 at android.os.AsyncTask$2.call(AsyncTask.java:295)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 at java.lang.Thread.run(Thread.java:818)
04-29 11:28:00.893 12314-12314/? E/es.gob.afirma: Error desconocido al cifrar el resultado de la firma
java.lang.NullPointerException: Attempt to get length of null array
 at es.gob.afirma.android.crypto.CipherDataManager.getNeededPaddingAsString(CipherDataManager.java:118)
 at es.gob.afirma.android.crypto.CipherDataManager.cipherData(CipherDataManager.java:109)
 at es.gob.afirma.android.WebSignActivity.onSigningSuccess(WebSignActivity.java:481)
 at es.gob.afirma.android.SignFragmentActivity.onSignSuccess(SignFragmentActivity.java:184)
 at es.gob.afirma.android.crypto.SignTask.onPostExecute(SignTask.java:202)
 at es.gob.afirma.android.crypto.SignTask.onPostExecute(SignTask.java:38)
 at android.os.AsyncTask.finish(AsyncTask.java:651)
 at android.os.AsyncTask.-wrap1(AsyncTask.java)
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
 at android.os.Handler.dispatchMessage(Handler.java:111)
 at android.os.Looper.loop(Looper.java:207)
 at android.app.ActivityThread.main(ActivityThread.java:5728)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by anadal-fundaciobit** [comment]
No es posava bé el tipus de firma a realitzar quan era mòbil (faltava el tri de firma trifàsica): PAdEstri, XAdEStri i CAdEStri
