### ISSUE TITLE
Error rebutjant i Esborrant peticions de Firma

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#429]
Des de la DGMAD ens comenten un error rebutjant i esborrant algunes peticions de Firma

L'error que surt és:
`
2020-05-06 12:50:51,488 ERROR [es.caib.portafib.logic.events.FirmaEvent] (http-10.215.9.230-18080-40) Error en signAnnexos(): failed to lazily initialize a collection of role: es.caib.portafib.jpa.PeticioDeFirmaJPA.annexs, no session or session was closed
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: es.caib.portafib.jpa.PeticioDeFirmaJPA.annexs, no session or session was closed
        at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:380)
        at org.hibernate.collection.AbstractPersistentCollection.throwLazyInitializationExceptionIfNotConnected(AbstractPersistentCollection.java:372)
        at org.hibernate.collection.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:119)
        at org.hibernate.collection.PersistentSet.size(PersistentSet.java:162)
        at es.caib.portafib.logic.events.FirmaEvent.signAnnexos(FirmaEvent.java:179)
        at es.caib.portafib.logic.events.FirmaEvent.<init>(FirmaEvent.java:153)
        at es.caib.portafib.logic.events.FirmaEventList.peticio_rebutjada(FirmaEventList.java:70)
        at es.caib.portafib.logic.PeticioDeFirmaLogicaEJB.rebutjarADEN(PeticioDeFirmaLogicaEJB.java:2724)
`

Pareix un error en els Annexes. Crear una petició i intentar rebutjar-la i/o esborrar-la a veure si es pot reproduir l'error.

**Comment by areus-fundaciobit** [comment]
Són errors derivats de la #316 implementada a la versió 2.0.1, en principi amb el darrer commit de 26 de setembre 2019 ja hauria d'estar corregit
