### ISSUE TITLE
NullPointerException per mor del fitltre de certificats

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#456]
Ens fan arribar aquesta traça:

    java.lang.NullPointerException
        at java.io.StringReader.<init>(StringReader.java:33)
        at org.fundaciobit.plugins.signatureserver.miniappletutils.MiniAppletUtils.matchFilter(MiniAppletUtils.java:379)
        at org.fundaciobit.plugins.signatureweb.miniappletinserversia.MiniAppletInServerSIASignatureWebPlugin.filter(MiniAppletInServerSIASignatureWebPlugin.java:155)
        at org.fundaciobit.plugins.signatureweb.miniappletinserversia.MiniAppletInServerSIASignatureWebPlugin.filter(MiniAppletInServerSIASignatureWebPlugin.java:126)
        at es.caib.portafib.back.controller.common.SignatureModuleController.selectSignModules(SignatureModuleController.java:180)

El problema estaria en que el filtre de certificats val nul. Per les firmes normals això no passa mai, perquè és processa. Però per les firmes múltiples es va canviar el codi per tenir en compte que no s'havia de deixar signar si el filtre no era el mateix per totes les firmes, i aquí no es va tenir en compte que dins la BDD Oracle si el camp del filtre de certificats es buid retornarà null

**Comment by areus-fundaciobit** [comment]
s'ha afegit el mateix procés de cleanFiltreCertificats que es feia sempre, i que s'havia omès quan es va fer el canvi per processar que el filtre fos el mateix en firmes múltiples
