### ISSUE TITLE
L'API REST V2 ASYNC falla quan el profile és null o buid

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#458]
En principi l'API REST V2 ASYNC ha de soportar que no s'indiqui perfil de firma, i en aquest cas, emprar el perfil de firma assignat a l'ususari aplicació, comprovant abans que aquest sigui únic.

Però es produeix una excepció si el valor de profileCode dins el request és null:

```
11:05:37,310 ERROR [RestApiFirmaAsyncSimpleV2Controller] S'ha fet una cridada REST amb l┤usuari aplicaci¾ fundaciobit_rcaib per‗ s'ha indicat un perfil de firma null o buit.. Consulti amb l'Administrador.
org.fundaciobit.genapp.common.i18n.I18NException: genapp.comodi
        at es.caib.portafib.logic.ConfiguracioUsuariAplicacioLogicaEJB.getPerfilDeFirma(ConfiguracioUsuariAplicacioLogicaEJB.java:135)
        at es.caib.portafib.logic.ConfiguracioUsuariAplicacioLogicaEJB.getConfiguracioFirmaPerApiFirmaAsyncSimple(ConfiguracioUsuariAplicacioLogicaEJB.java:440)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by areus-fundaciobit** [comment]
Ara es comprova si el profile és null o buid, i en aquest cas es cerca que hi hagi un únic perfil associat amb l'usuari aplicació que tengui una configuració establerta per l'API ASYNC REST V2
