### ISSUE TITLE
Possibles problemes de concurrència al procés de firma

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#509]
Molts dels plugins de firma web poden tenir problemes de concurrència.

En principi la classe `AbstractSignatureWebPlugin` defineix el Map `infosign` i sincronitza tots els accessos (a excepció de a `internalGetActiveTransactions` a la línia 532 on també caldria sincronitzar l'accés.

Però moltes de les subclasses defineixen estructures tipus Map addicionals per emmagatzemar caches o informacions de les transaccions sense sincronitzar-hi l'accés, cosa que podria donar lloc a `ConcurrentModificationException`.

Caldria canviar tots aquests maps per `ConcurrentHashMap` per evitar aquests problemes. I revisar si hi ha variables que requereixin l'ús de `volatile`. En el cas de `AbstractSignatureWebPlugin`, `infosign` també seria millor passar-lo a `ConcurrentHashMap` i així evitar els blocs `synchronized`.

**Comment by areus-fundaciobit** [comment]
Generant un test amb firmes concurrents es produeix el següent error. Per tant, no només seria als plugins, sinó també al SignatureModuleController

java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
        at java.util.HashMap$KeyIterator.next(HashMap.java:956)
        at es.caib.portafib.back.controller.common.SignatureModuleController.getPortaFIBSignaturesSet(SignatureModuleController.java:659)
        at es.caib.portafib.back.controller.common.SignatureModuleController.getSignaturesSetByID(SignatureModuleController.java:636)
        at es.caib.portafib.back.controller.common.PassarelaDeFirmaController.finalProcesDeFirmaReal(PassarelaDeFirmaController.java:231)

**Comment by areus-fundaciobit** [comment]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$KeyIterator.next(HashMap.java:956)
	at es.caib.portafib.logic.passarela.PassarelaDeFirmaWebEJB.checkExpiredSignaturesSet(PassarelaDeFirmaWebEJB.java:1078)
	at es.caib.portafib.logic.passarela.PassarelaDeFirmaWebEJB.readSignaturesSet(PassarelaDeFirmaWebEJB.java:974)
	at es.caib.portafib.logic.passarela.PassarelaDeFirmaWebEJB.getSignaturesSetFullByTransactionID(PassarelaDeFirmaWebEJB.java:442)
