### ISSUE TITLE
Problema amb la connexió TLSv1.2 amb viafirma

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#554]
- El mínim ara per connectar a viafirma és TLSv1.2
 - Java 7 suporta TLSv1.2 però per defecte no està activat.
 - Sembla que funcionant amb Java 7 la llibreria client de fortress: viafirma-fortress-sdk-java no activa el TLSv1.2
 
He provat el següent:
 
```
SSLContext ctx = SSLContext.getInstance("TLSv1.2");
ctx.init(null, null, null);
SSLContext.setDefault(ctx);

URL url = new URL("https://pre.firmacloud.com/fortress/");
HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
connection.connect();
System.out.println(connection.getResponseCode());
```

   
Aquesta prova funciona correctament amb Java 7 i imprimeix 200.
Les 3 primeres línies del SSLContext serveixen per activar programàticament TLSv1.2 sobre Java 7
 
També sense aquestes tres línies, però passant la propietat "-Dhttps.protocols=TLSv1.2" per paràmetre, la connexió així funciona correctament.
 
Però quan feim la connexió emprant les llibrerires "viafirma-fortress-sdk-java" versió 4.6.2 (la versió 4.8.x ja requereix Java 8), ni d'una manera ni l'altre aconseguim que empri TLSv1.2 i sempre surt l'error de protocol.
 

> com.viafirma.fortress.sdk.exception.NetworkException: Received fatal alert: protocol_version
>     at com.viafirma.fortress.sdk.FortressApi.executeCall(FortressApi.java:260)
>     at com.viafirma.fortress.sdk.FortressApi.getAccessToken(FortressApi.java:172)
>     at com.viafirma.fortress.sdk.FortressApi.getAccessToken(FortressApi.java:168)
>     at org.fundaciobit.pluginsib.signatureweb.fortress.test.TestFortress.testAuth(TestFortress.java:42)
> Caused by: javax.net.ssl.SSLException: Received fatal alert: protocol_version
>     at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
>     at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
>     at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
>     at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
>     at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
>     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
>     at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
>     at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:239)
>     at okhttp3.internal.io.RealConnection.establishProtocol(RealConnection.java:196)
>     at okhttp3.internal.io.RealConnection.buildConnection(RealConnection.java:171)
>     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
>     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:187)
>     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:123)
>     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:93)
>     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:296)
>     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
>     at okhttp3.RealCall.getResponse(RealCall.java:243)
>     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
>     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
>     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
>     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
>     at okhttp3.RealCall.execute(RealCall.java:57)
>     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
>     at com.viafirma.fortress.sdk.FortressApi.executeCall(FortressApi.java:253)

Sembla que el problema vendria d'aquí:

https://github.com/square/okhttp/issues/4086

**Comment by areus-fundaciobit** [comment]
Declarat explicitament les dependències de `okhttp3` amb la versió `3.12.12` resol el problema. També s'ha hagut de tocar el test perquè per defecte `HtmlUnit` tampoc carregava bé el TLSv1.2

**Comment by areus-fundaciobit** [comment]
Sembla que s'han modificat els algoritmes de xifratge disponibles al servidor i es produeix un "handshake failure". El problema és que OkHttp només empra un subconjunt dels algoritmes suportats per Java 7, i entre aquests no n'hi ha cap suportat pel servidor:

Els algoritmes suportats per la intersecció entre Java 7 i OkHttp són els següents 5:

    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA    
    TLS_RSA_WITH_AES_256_CBC_SHA
    TLS_RSA_WITH_AES_128_CBC_SHA
    SSL_RSA_WITH_3DES_EDE_CBC_SHA

Dels quals només els 2 primers surten recomanats a https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices

Mentre que els algoritmes suportats actualment pel servidor són:

	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
	TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
	TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256

Dels quals, només els dos darrers estan suportats per Java 7.

Per tant, les dues possibles solucions serien:

 - Activar els següents al servidor suportats per la intersecció entre Java 7 i OkHttp i considerats segurs:

	`TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`
	`TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`

 - Fer un pegat a l'API per customitzar la instanciació de Okhttp per suportar els algoritmes del servidor suportats per Java 7:
 
	`TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384`
	`TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256`

**Comment by areus-fundaciobit** [comment]
s'ha fet la sol·lució 2 temporal. fins que es migri a Java 11
