### ISSUE TITLE
Error de constraint SQL creant una petició de firma des de API Indra

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#649]
Sembla que hi ha qualque registre que no es crea o no es crea en l'odre que toca, bota el següent error en crear la petició de firma:

```
14:11:38,747 INFO  [es.caib.portafib.ws.v1.PortafirmasIndraImpl] (default task-1) Executing operation  uploadDocument
14:11:38,966 INFO  [es.caib.portafib.logic.WebServicesMethodsEJB] (default task-1) getCustodyInfoOnCreatePeticio ci=null
14:11:39,008 INFO  [es.caib.portafib.logic.WebServicesMethodsEJB] (default task-1)  FILE ORIG = C:\Users\anton\projectes\portafib\filesystem\243750     true    12899   Fri Aug 13 14:11:38 CEST 2021
14:11:39,014 INFO  [es.caib.portafib.logic.utils.PdfUtils] (default task-1) Numero mÓxim de firmants per taula de firmes: 10
14:11:39,048 INFO  [es.caib.portafib.logic.utils.PdfUtils] (default task-1) XYZ ZZZ Comprovant si es PDF/Ax ...
14:11:39,351 INFO  [org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl] (default task-1) HHH000010: On release of batch it still contained JDBC statements
14:11:39,352 ERROR [org.hibernate.engine.jdbc.batch.internal.BatchingBatch] (default task-1) HHH000315: Exception executing batch [java.sql.BatchUpdateException: ORA-02291: integrity constraint (PORTAFIB.PFI_ANNEX_PETIFIRMA_FK) violated - parent key not found
], SQL: insert into pfi_annex (adjuntar, firmar, fitxerid, peticiodefirmaid, annexid) values (?, ?, ?, ?, ?)
14:11:39,353 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-1) SQL Error: 2291, SQLState: 23000
14:11:39,353 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-1) ORA-02291: integrity constraint (PORTAFIB.PFI_ANNEX_PETIFIRMA_FK) violated - parent key not found

14:11:39,360 ERROR [org.jboss.as.ejb3.invocation] (default task-1) WFLYEJB0034: EJB Invocation failed on component FirmaLogicaEJB for method public abstract java.lang.Long org.fundaciobit.genapp.common.query.ITableManager.count(org.fundaciobit.genapp.common.query.Where) throws org.fundaciobit.genapp.common.i18n.I18NException: javax.ejb.EJBTransactionRolledbackException: org.hibernate.exception.ConstraintViolationException: could not execute batch
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInCallerTx(CMTTxInterceptor.java:217)
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:390)
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:158)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
        at org.jboss.weld.core@3.0.6.Final-redhat-00004//org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:72)
        at org.jboss.as.weld.common@7.2.9.GA-redhat-00003//org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.component.interceptors.ShutDownInterceptorFactory$1.processInvocation(ShutDownInterceptorFactory.java:64)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ejb3@7.2.9.GA-redhat-00003//org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:67)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.as.ee@7.2.9.GA-redhat-00003//org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:438)
        at org.wildfly.security.elytron-private@1.6.8.Final-redhat-00001//org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:630)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:57)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
        at org.jboss.invocation@1.5.2.Final-redhat-00001//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
        at org.jboss.as.ee@7.2.9.GA-redhat-00003//org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:198)
        at org.jboss.as.ee@7.2.9.GA-redhat-00003//org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:185)
        at org.jboss.as.ee@7.2.9.GA-redhat-00003//org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:81)
        at deployment.portafib.ear.portafib-logic.jar//es.caib.portafib.logic.FirmaLogicaLocal$$$view3.count(Unknown Source)
        at deployment.portafib.ear.portafib-logic.jar//es.caib.portafib.logic.PeticioDeFirmaLogicaEJB.startNextSign(PeticioDeFirmaLogicaEJB.java:1587)
        at deployment.portafib.ear.portafib-logic.jar//es.caib.portafib.logic.PeticioDeFirmaLogicaEJB.start(PeticioDeFirmaLogicaEJB.java:762)
        at deployment.portafib.ear.portafib-logic.jar//es.caib.portafib.logic.WebServicesMethodsEJB.createAndStartPeticioDeFirma(WebServicesMethodsEJB.java:48)
```

**Comment by areus-fundaciobit** [comment]
No és un error específic d'aquesta API, sinó que el provoca fixar la propietat `hibernate.order_inserts` a `true`. Sembla que és una part que s'ha canviat molt de Hibernate, i amb la versió actual 5.2, així com estan definits els mappings a Hibernate, fent un doble mapping tant de la clau forana com de l'associació d'objectes, i  en aquest darrer cas, el fet que el `@JoinColumn` de les relacions tengui la propietat `insertable` a `false`, fa que no pugui reconèixer correctament les dependències i per tant l'ordre amb que cal fer els inserts. Si es fixa l' `insertable` a `true` si funciona. Però això suposa deshabilitar l'altre propietat acabada amb `ID` que mapeja la clau forana.  I suposa canviar així com es gestionen totes les relacions actualment. Per tant, es deshabilitar `hibernate.order_inserts`
