### ISSUE TITLE
Error en les APIs REST autenticant l'usuari/password

### ISSUE THREAD

**Issue by areus-fundaciobit** [GovernIB/portafib#651]
La invocació de les APIs REST llança el següent error:

```
Caused by: java.lang.NoClassDefFoundError: org/jboss/web/tomcat/security/login/WebAuthentication
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.controller.rest.RestUtils.authenticateUsernamePassword(RestUtils.java:197)
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.controller.rest.RestUtils.autenticateUsrApp(RestUtils.java:85)
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.controller.rest.apifirmaasyncsimple.v2.RestApiFirmaAsyncSimpleV2Controller.createAndStartSignatureRequest(RestApiFirmaAsyncSimpleV2Controller.java:501)
```

**Comment by areus-fundaciobit** [comment]
S'ha substituint l'ús que es feia de `WebAuthentication` per el nou (Sevlet 3.0) mètode `login` de `HttpServletRequest`, però el problema de fons sembla ser el següent:

Les URLs cap a les APIs REST, estan dins el bloc de URLS "no protegides", sense `security-constraint`, perquè l'autenticació es fa programàticament. Llavors el comportament sembla ser diferent
 - Amb JBoss 5.2, no disparen una autenticació, encara que hi hagi capçalera d'autenticació a la petició, l'autenticació es fa programàticament.
 - Amb JBoss 7.2, si hi ha capçalera es dispara l'autenticació, per tant al moment que arriba a fer l'autenticació programàtica, aquesta ja s'ha fet.

En principi el comportament segon no suposaria un problema, però el fet de disparar-se l'autenticació de servidor, fa que també es dispari l'`AuthenticationSuccessListener` de Spring que no està preparat per aquests casos d'autenticació d'aplciació, i ho tracta com si fos un Usuari Persona enlloc d'un Usuari Aplicació

Si es confirma que aquest és el problema, caldrà cercar una d'aquestes dues opcions:
 - Mirar si hi ha cap opció de configuració per evitar que JBoss dispari l'autenticació, i per tant es comporti com el JBoss 5.2
 - Adaptar l`AuthenticationSuccessLlistener` a aquests casos.

**Comment by areus-fundaciobit** [comment]
S'ha resolt l'error inical de "ClassNotFound" però igualment caldrà fer un canvi. Atès que la nova platforma presentarà dificultats a l'hora de configurar l'autenticació ja que un mòdul WAR s'ha de configurar per autenticació de normal o de serveis web, optarem per separar els mòduls REST en un WAR a part

**Comment by areus-fundaciobit** [comment]
s'ha fet una petita modificació a l'AuthenticationSuccessListener per tal que no entri en conflicte amb els logins de usuaris aplicació. En qualsevol cas, caldrà reestudiar-ho
