### ISSUE TITLE
Problemes amb firmes XAdES.

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#742]
Problemes amb firmes XAdES.

```
2022-07-01 13:49:12,131 ERROR [es.caib.portafib.logic.passarela.PassarelaDeFirmaEnServidorEJB] (http-10.215.29.9-18080-14) Error desconegut intentant determinar si un XAdES dettached inclou el document original com a element: org.apache.xerces.dom.DeferredTextImpl cannot be cast to org.w3c.dom.Element
es.caib.portafib.logic.ValidacioException: Error desconegut intentant determinar si un XAdES dettached inclou el document original com a element: org.apache.xerces.dom.DeferredTextImpl cannot be cast to org.w3c.dom.Element
        at es.caib.portafib.logic.ValidacioCompletaFirmaLogicaEJB.validateCompletaFirma(ValidacioCompletaFirmaLogicaEJB.java:68)
        at sun.reflect.GeneratedMethodAccessor836.invoke(Unknown Source)
```

**Comment by anadal-fundaciobit** [comment]
Solucionat. Comprovar tipus abans de fer CAST
