### ISSUE TITLE
Error al entrar amb ROLE_ADMIN i BBDD neta

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#749]
Error al entrar amb ROLE_ADMIN i BBDD neta #749 

10:07:49,085 ERROR [org.apache.jsp.error_jsp] (default task-4) Error llegint informaci¾ del plugin de UserInformation: null: es.caib.portafib.back.security.LoginException: Error llegint informaci¾ del plugin de UserInformation: null
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.security.AuthenticationSuccessListener.onApplicationEvent(AuthenticationSuccessListener.java:233)
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.security.AuthenticationSuccessListener.onApplicationEvent(AuthenticationSuccessListener.java:49)
        at deployment.portafib.ear.portafib-back.war//org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
...
Caused by: java.lang.NullPointerException
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.security.AuthenticationSuccessListener.onApplicationEvent(AuthenticationSuccessListener.java:163)
        ... 79 more

![imatge](https://user-images.githubusercontent.com/17084256/189604366-a4f16426-74c3-4312-acdc-e9ec575da0bf.png)

**Comment by anadal-fundaciobit** [comment]
Al final ha resultat que el KeyCloak no estava ben configurat (no tenia mapping per NIF).
S'ha afegit un missatge més descriptiu:

![imatge](https://user-images.githubusercontent.com/17084256/189620879-cdd68fb5-490f-4847-ad6d-a3bcc40acde6.png)
