### ISSUE TITLE
Error al crear un usuari aplicació

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#801]
```
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at deployment.portafib.ear.portafib-ejb.jar//es.caib.portafib.logic.validator.UsuariAplicacioLogicValidator.validate(UsuariAplicacioLogicValidator.java:38)
	at deployment.portafib.ear.portafib-ejb.jar//es.caib.portafib.logic.validator.UsuariAplicacioBeanLogicValidator.validate(UsuariAplicacioBeanLogicValidator.java:36)
	at deployment.portafib.ear.portafib-ejb.jar//es.caib.portafib.logic.UsuariAplicacioLogicaEJB.createFull(UsuariAplicacioLogicaEJB.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.as.ee@7.2.0.GA-redhat-00005//org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52)
	at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation@1.5.1.Final-redhat-1//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
```

![imatge](https://github.com/GovernIB/portafib/assets/17084256/096541d2-8ece-4b1f-adf0-c4b295d126fb)

**Comment by anadal-fundaciobit** [comment]
Solucionat.
