### ISSUE TITLE
Error al donar d'alta Tipus Documental 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#867]
Error al donar d'alta Tious Documental  revisar també per que no s'activa el menú ...

```
13:50:17,979 ERROR [es.caib.portafib.back.controller.admin.GestioTipusDocumentAdminController] (default task-21) Ha ocorregut un error en actualitzar Tipus de Document amb ID igual a 69: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap'): java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Long (java.lang.String and java.lang.Long are in module java.base of loader 'bootstrap')
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.controller.admin.GestioTipusDocumentAdminController.postValidate(GestioTipusDocumentAdminController.java:204)
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.controller.webdb.TipusDocumentController.editarTipusDocumentPost(TipusDocumentController.java:437)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

![imatge](https://github.com/user-attachments/assets/f9743e24-c6f1-47cb-b435-57659e869d3d)

**Comment by anadal-fundaciobit** [comment]
Solucionat.
