### ISSUE TITLE
Error firmant XADES amb @autofirma 

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#898]
La Firma amb ApiFirmaWeb Simple Síncrona falla amb un SAF27 quan es vol fer una firma XAdES emprant el Plugin de Autofirma.

```

11:38:41,257 INFO  [es.caib.portafib.back.controller.common.SignatureModuleController] (default task-128) XYZ ZZZ  SignatureModuleController:absoluteRequestPluginBasePath => http://anadal:8080/portafibback/public/signmodule/requestPlugin/wC55b2x-nH94n3PaExWdisDX2aFR/-1
11:38:41,257 INFO  [es.caib.portafib.back.controller.common.SignatureModuleController] (default task-128) XYZ ZZZ  SignatureModuleController:relativeRequestPluginBasePath => /portafibback/public/signmodule/requestPlugin/wC55b2x-nH94n3PaExWdisDX2aFR/-1
11:38:41,308 INFO  [es.gob.afirma] (default task-128) Prefirma XAdES - Firma - INICIO
11:38:41,545 WARNING [es.gob.afirma] (default task-128) No se ha podido establecer una propiedad de seguridad 'http://javax.xml.XMLConstants/property/accessExternalDTD' en la factoria XML
11:38:41,545 WARNING [es.gob.afirma] (default task-128) No se ha podido establecer una propiedad de seguridad 'http://javax.xml.XMLConstants/property/accessExternalSchema' en la factoria XML
11:38:41,546 WARNING [es.gob.afirma] (default task-128) No se ha podido establecer una propiedad de seguridad 'http://javax.xml.XMLConstants/property/accessExternalStylesheet' en la factoria XML
11:38:41,546 WARNING [es.gob.afirma] (default task-128) Error en una de las firmas del lote (d0M1NWIyeC1uSDk0bjNQYUV4V2Rpc0RYMmFGUnww), se continua con el siguiente elemento: java.lang.UnsupportedOperationException: El formato de firma 'XAdES' no esta soportado: java.lang.UnsupportedOperationException: El formato de firma 'XAdES' no esta soportado
        at deployment.portafib.ear//es.gob.afirma.signers.xml.Utils.checkIllegalParams(Utils.java:432)
        at deployment.portafib.ear//es.gob.afirma.signers.xades.XAdESSigner.sign(XAdESSigner.java:344)
        at deployment.portafib.ear//es.gob.afirma.triphase.signer.xades.XAdESTriPhaseSignerServerSide.preSign(XAdESTriPhaseSignerServerSide.java:209)
        at deployment.portafib.ear//es.gob.afirma.triphase.signer.processors.XAdESTriPhasePreProcessor.preProcessPre(XAdESTriPhasePreProcessor.java:186)
        at deployment.portafib.ear//es.gob.afirma.triphase.signer.processors.XAdESTriPhasePreProcessor.preProcessPreSign(XAdESTriPhasePreProcessor.java:109)
        at deployment.portafib.ear//es.gob.afirma.signers.batch.SingleSignPreProcessor.getPreSign(SingleSignPreProcessor.java:109)
        at deployment.portafib.ear//es.gob.afirma.signers.batch.SingleSignPreProcessor.doPreProcess(SingleSignPreProcessor.java:49)
        at deployment.portafib.ear//es.gob.afirma.signers.batch.SingleSign.doPreProcess(SingleSign.java:271)
        at deployment.portafib.ear//es.gob.afirma.signers.batch.SignBatchSerial.doPreBatch(SignBatchSerial.java:57)
        at deployment.portafib.ear//es.gob.afirma.signers.batch.server.BatchPresigner.service(BatchPresigner.java:116)
        at javax.servlet.api@1.0.0.Final-redhat-1//javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at deployment.portafib.ear//org.fundaciobit.pluginsib.signatureweb.afirmatriphaseserver.AfirmaTriphaseSignatureWebPlugin.batchPreSigner(AfirmaTriphaseSignatureWebPlugin.java:2380)
        at deployment.portafib.ear//org.fundaciobit.pluginsib.signatureweb.afirmatriphaseserver.AfirmaTriphaseSignatureWebPlugin.commonRequestGETPOST(AfirmaTriphaseSignatureWebPlugin.java:317)
        at deployment.portafib.ear//org.fundaciobit.pluginsib.signatureweb.afirmatriphaseserver.AfirmaTriphaseSignatureWebPlugin.requestPOST(AfirmaTriphaseSignatureWebPlugin.java:293)
        at deployment.portafib.ear//org.fundaciobit.pluginsib.signatureweb.api.AbstractSignatureWebPlugin.requestPOST(AbstractSignatureWebPlugin.java:239)
```

**Comment by anadal-fundaciobit** [comment]
Solucionat parcialment.
La solució definitiva arribarà amb la migració dels modes de firma definits a "[Ampliar els Modes de Firma](https://github.com/GovernIB/portafib/issues/825)"
