### ISSUE TITLE
Error en dispositiu mòbil al seleccionar "Vista ordenador"

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#906]
Error en dispositiu mòbil al seleccionar "Vista ordenador" en la pantalla de Peticions Pendents de  Destinatari

![image](https://github.com/user-attachments/assets/bc03c2c5-0898-4d71-9a30-15ed378075a1)

```
Caused by: java.lang.NullPointerException
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.controller.AbstractEstatDeFirmaDestDeleColaController.postList(AbstractEstatDeFirmaDestDeleColaController.java:2073)
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.controller.webdb.EstatDeFirmaController.llistat(EstatDeFirmaController.java:176)
        at deployment.portafib.ear.portafib-back.war//es.caib.portafib.back.controller.webdb.EstatDeFirmaController.llistatPaginat(EstatDeFirmaController.java:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:204)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:854)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:765)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at deployment.portafib.ear.portafib-back.war//org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        ... 95 more
```

**Comment by anadal-fundaciobit** [comment]
Em estudiat el tema i realment no és un error. Un cop has entrat a la pàgina com a dispositiu mòbil no es pot canviar a "vista ordinador" ja que la pàgina s'ha configurat (inicialitzat) per dispositiu mòbil.

Prova el següent:
(1) Tanca el Navegador (no amagar, sinó tancar)
(2) Torna'l a obrir
(3) Ves a la pàgina de presentació de PortaFIB
(4) Canvia a "vista ordinador"
(5) Si ara vas a la pipella Destinatari, a la llista de Peticions Pendents ja no et donarà l'error.

**Comment by anadal-fundaciobit** [comment]
Afegit Parxe.
