### ISSUE TITLE
NullPointerException en el XadesSignatureExtractor fent feina sobre un fitxer PDF

### ISSUE THREAD

**Issue by anadal-fundaciobit** [GovernIB/portafib#916]
NullPointerException en el XadesSignatureExtractor fent feina sobre un fitxer PDF

```
 2024-11-19 12:36:41,795 ERROR [es.caib.portafib.logic.signatures.XadesSignatureExtractor] (default task-2902) Error obtenint signatures XADES: java.lang.NullPointerException
      at deployment.portafib.ear.portafib-ejb.jar//es.caib.portafib.logic.signatures.SignatureFactory.getSignature(SignatureFactory.java:26)
      at deployment.portafib.ear.portafib-ejb.jar//es.caib.portafib.logic.signatures.XadesSignatureExtractor.extract(XadesSignatureExtractor.java:88)
      at deployment.portafib.ear.portafib-ejb.jar//es.caib.portafib.logic.signatures.SignatureServiceEJB.getSignatures(SignatureServiceEJB.java:47)
```

Veure que passa.

**Comment by anadal-fundaciobit** [comment]
També s'ha solucionat un problema de previsualització quan el fitxer no té extensió.

**Comment by anadal-fundaciobit** [comment]
Solucionat.
